function link() {location.replace("/");}
function linkqqjago() {location.replace("https://www.qqjago.id/");}
function linkalibababet() {location.replace("https://rebrand.ly/f4c4ba/");}
function linkmagnum188() {location.replace("https://jali.me/magnum188-link");}
function linkbandar55() {location.replace("https://alternatifbandar55.site/");}
function linkalfa138() {location.replace("https://t.ly/daftar-alfa138");}
function linkmewah99() {location.replace("https://rebrandly.one/mewah99-login");}
function linkqqstarvegas() {location.replace("https://qqamplagi.click/");}
function linkbig368() {location.replace("https://mylink.ly/big368");}
function linkidn33() {location.replace("https://urlq.link/ampidn33");}
function linkqqfullbet() {location.replace("https://tinyurl.com/ampqqfullbet");}
function linkonestepwin() {location.replace("https://jituwin16a.com/");}
function linkm11bet() {location.replace("https://dub.sh/m11bet");}
function linkhokibet() {location.replace("https://hoki.bio/v1/");}
function linkibosport() {location.replace("https://klik.bet/ibosport-v1");}
function linkqq1889() {location.replace("https://www.qq1889.fyi/");}
function linkqq88asia() {location.replace("https://enjoythegame.online/qq88asia");}
function linkqq8821() {location.replace("https://enjoythegame.online/qq8821");}
function linkgoldwin678() {location.replace("https://goldwin678code.com/");}
function linkqqkuda() {location.replace("https://cutt.ly/Daftar-QQKuda");}
function linkqqmilan() {location.replace("https://bit.ly/M1l4N");}
function linkqq2889() {location.replace("https://cutt.ly/qq2889");}
function linkqqdewa() {location.replace("https://cepat.io/qqdewalogin1");}
function linkqqemas() {location.replace("https://lyte.page/qqemas");}
function linkqqnusa() {location.replace("https://qqnusamew.net/");}
function linkqqmacan() {location.replace("https://linkqqmacan.com/");}
function linkluxury777() {location.replace("https://linkluxury777.com/");}
function linkqq1221() {location.replace("https://qq1221joy.info/");}
function linkqq101() {location.replace("https://lkgw.net/qq101-altbrand");}
function linkqqkopidarat() {location.replace("https://youtube.com/");}
function linkarenacuan99() {location.replace("https://youtube.com/");}
function linkqqmybet() {location.replace("https://youtube.com/");}
function linkqqtopan() {location.replace("https://youtube.com/");}
function link88idr() {location.replace("https://rebrand.ly/88idrlogin-AMP");}
function link1001win() {location.replace("https://vipakses.com/1001newAMP-LOGIN");}
function linkqqangpao() {location.replace("https://vipakses.com/LPLOGINQQANGPAO");}
function linkqq888bet() {location.replace("https://qq888bet5jm.com/");}
function linkqqbonus() {location.replace("https://lkgw.net/qqbonus-altbrand");}
function linkqq188() {location.replace("https://lkgw.net/qq188-altbrand");}
function linkqq724() {location.replace("https://vipakses.com/LoginQQ724");}
function linkqq288() {location.replace("https://lkgw.net/qq288-altbrand");}
function linkqq828() {location.replace("https://lkgw.net/qq828-altbrand");}
function linkqq801() {location.replace("https://vipakses.com/Login801");}
function linkqq808() {location.replace("https://vipakses.com/LoginQQ808");}
function linkqq882() {location.replace("https://lkgw.net/qq882-altbrand");}
function linkqqberak() {location.replace("https://lkgw.net/qqberak-alternatif");}
function linkqq88pro() {location.replace("https://rebrand.ly/qq88pro1");}
function linkqq303() {location.replace("https://rebrand.ly/QQ303-Login");}
function linkqqfortuna() {location.replace("https://rebrand.ly/qqfortuna-login");}
function linkqqbetwin() {location.replace("https://qqbetwin69q.com/");}
function linkqqfunbet() {location.replace("https://qqfunbet12p.com/");}
function linkqqvegas() {location.replace("https://qqvegas3kl.com/");}
function linkqqkingbet() {location.replace("https://www.qqkingbet24.com/");}
function linkqqextra() {location.replace("https://qqextra21k.com/");}
function linkqqterang() {location.replace("https://qqterang24j.com/");}
function linkqq7887() {location.replace("https://qq7887jru.com/");}
function linkqqfunwin() {location.replace("https://rebrand.ly/funwin7");}
function linkqqmegah() {location.replace("https://rebrand.ly/megah28");}
function linkqqfun77() {location.replace("https://qqfun77ak7.com/");}
function linkqq999bet() {location.replace("https://qq999bet99w.com/");}
function linkqq7997() {location.replace("https://qq7997bs2.com/");}
function linkqqbos99() {location.replace("https://qqbos99p1.com/");}
function linkqq8889() {location.replace("https://rebrand.ly/loginqq8889");}
function linkqq1x2() {location.replace("https://lkgw.net/qq1x2-altbrand");}
document.getElementById('yourform').submit();
